# This is the free version of kill-assist plugin
# Developer: [kuzqi] discord --> kuzqi
#
# for more features you can buy the premium version.
#
# PREMIUM FEATURES $ ADDONS:
# Support all minecraft versions [1.8x-1.21x]
# ActionBars supported
# High-End optmization for server performance
# Full customizable configs/messages
# Debug mode
# Custom support
# And more...
#
Premium-version: "soon"
discord: "https://discord.gg/3nyXGTue7Z"